# Numpy Re-Master

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Creating simple array
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [3]:
print(np.__version__) # Check np version

2.3.0


In [4]:
arr = np.array(42)
print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


### Check dimensions

In [5]:
print(arr.ndim) # ndim to check dimensions

0


In [6]:
arr = np.array([[23, 513], [2, 4], [65, 64]])
print(arr.ndim)

2


In [7]:
arr = np.array([5, 12, 54, 1], ndmin=4)
print(arr, arr.ndim)

[[[[ 5 12 54  1]]]] 4


## Indexing

In [8]:
arr = np.array([1, 2, 3, 4])
print(arr[:-1])

[1 2 3]


In [9]:
print(arr) # Not changes

[1 2 3 4]


In [10]:
print(arr[::-1])

[4 3 2 1]


In [11]:
print(arr)

[1 2 3 4]


## Slicing
[start:end:step]

In [12]:
arr = np.array([1, 3, 5, 0, 9, 18, 19, 7])
print(arr[3:-1])

[ 0  9 18 19]


In [13]:
print(arr[1:-1:2])

[ 3  0 18]


In [14]:
print(arr[1:-1:1])

[ 3  5  0  9 18 19]


## Data type
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [15]:
arr = np.array([1, 2, 4, 5], dtype="S")
print(arr)

[b'1' b'2' b'4' b'5']


In [16]:
arr = np.array([4, 1, 5, 13], dtype="i4")
print(arr)

[ 4  1  5 13]


In [17]:
# Convert data dtype
print(arr.astype('f'))

[ 4.  1.  5. 13.]


In [18]:
print(arr.astype('S'))

[b'4' b'1' b'5' b'13']


In [19]:
print(arr.astype(bool))

[ True  True  True  True]


## Copy and View

In [20]:
arr = np.array([5, 7, 19])
arr2 = arr.copy() # copy array
print(arr2)
arr2 = np.array([5, 78])
print(arr2)
print(arr)

[ 5  7 19]
[ 5 78]
[ 5  7 19]


In [21]:
arr2 = arr.view() # view change the original one
print(arr2)
print(arr)
arr2[0] = 90
print(arr2)
print(arr)


[ 5  7 19]
[ 5  7 19]
[90  7 19]
[90  7 19]


In [22]:
## reshape array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print(arr)
arr = arr.reshape(2, 5)
print(arr)

[1 2 3 4 5 6 7 8 9 0]
[[1 2 3 4 5]
 [6 7 8 9 0]]


In [23]:
# Flattening array
print(arr)
arr = arr.reshape(-1)
print(arr)

[[1 2 3 4 5]
 [6 7 8 9 0]]
[1 2 3 4 5 6 7 8 9 0]


In [24]:
## Stack
arr = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr3 = np.stack((arr, arr2), axis=1) # stack two array
print(arr3)

[[1 4]
 [2 5]
 [3 6]]


In [25]:
arr3 = np.hstack((arr, arr2))
print(arr3)

[1 2 3 4 5 6]


In [27]:
## Filters
arr = np.array([4, 1])
f = [True, False] # Filter need to be same
print(arr[f])

[4]
